# Generated by Django 5.0.2 on 2024-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourtask',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ourtask',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
